trigger:
  branches:
    include:
      - master
  #tags:
  #  include:
  #  - v*

strategy:
  matrix:
    linux:
      imageName: "ubuntu-20.04"
    mac:
      imageName: "macOS-10.15"
    windows:
      imageName: "windows-2019"

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - bash: |
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      echo ">>> Started xvfb"
    displayName: Start xvfb
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

  - bash: |
      echo ">>> Compile vscode-test"
      npm install
      npm run vscode:prepublish
      npm run test:coverage
    displayName: Run Tests
    env:
      DISPLAY: ":99.0"
