trigger:
  branches:
    include:
      - master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    linux-package:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macOS-latest"
    windows:
      imageName: "windows-latest"

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - bash: |
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      echo ">>> Started xvfb"
    displayName: Start xvfb
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

  - task: SonarCloudPrepare@1
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Job linux'))
    inputs:
      SonarCloud: "sonarcloud"
      organization: "prb28-github"
      scannerMode: "CLI"
      configMode: "file"

  - task: Npm@1
    inputs:
      command: "install"

  - bash: |
      echo ">>> Package"
      npm install -g vsce
      npm run coverage:disable
      vsce package
      cp *.vsix $(Build.ArtifactStagingDirectory)
    displayName: Package
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Job linux-package'))

  - bash: |
      echo ">>> Compile vscode-test"
      npm run vscode:prepublish
      npm run test:coverage
      npm run tslint
    displayName: Run Tests
    condition: and(succeeded(), ne(variables['Agent.JobName'], 'Job linux-package'))
    env:
      DISPLAY: ":99.0"

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: "out/**/test-results.xml"
    condition: and(succeededOrFailed(), eq(variables['Agent.JobName'], 'Job linux'))

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/*coverage.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/**/coverage"
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Job linux'))

  - bash: |
      echo ">>> Publish to coveralls"
      node_modules/.bin/coveralls < coverage/lcov.info
    displayName: Publish to Coveralls
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Job linux'))

  - task: PublishBuildArtifacts@1
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Job linux-package'))
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "extension"
      publishLocation: "Container"

  - task: SonarCloudAnalyze@1
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Job linux'))

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: "300"
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Job linux'))
